calculatorPlus/src/main/java/br/edu/vianna/plus/calculatorplus/controller/action/dto/RankingDTO.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.vianna.plus.calculatorplus.controller.action.dto;

import br.edu.vianna.plus.calculatorplus.util.Util;

/**
 *
 * @author daves
 */
public class RankingDTO {

    private String nome;
    private double bonus;
    private long tempo;
    private long numeroCompeticoes;

    public String getBonusFormatado() {
        return Util.formatarMoeda(bonus);
    }

    public RankingDTO() {
    }

    public RankingDTO(String nome, double bonus, long tempo, long numeroCompeticoes) {
        this.nome = nome;
        this.bonus = bonus;
        this.tempo = tempo;
        this.numeroCompeticoes = numeroCompeticoes;
    }
    
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public double getBonus() {
        return bonus;
    }

    public void setBonus(double bonus) {
        this.bonus = bonus;
    }

    public long getTempo() {
        return tempo;
    }

    public void setTempo(long tempo) {
        this.tempo = tempo;
    }

    public long getNumeroCompeticoes() {
        return numeroCompeticoes;
    }

    public void setNumeroCompeticoes(long numeroCompeticoes) {
        this.numeroCompeticoes = numeroCompeticoes;
    }
    
    

}

calculatorPlus/src/main/webapp/pages/home.jsp
<!--<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <img src="../assets/img/calc.png" style="border-radius: 10px">
            <h5 class="title">Calculator </h5>
            <p class="category">Competição de Calculadora</p>
        </div>
        <div class="card-body">
            <div class="typography-line">
                <h1>
                    <span>Header 1</span>The Life of Paper Dashboard </h1>
            </div>
            
            <div class="typography-line">
                <span>Quote</span>
                <blockquote>
                    <p class="blockquote blockquote-primary">
                        "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that?s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at."
                        <br>
                        <br>
                        <small>
                            - Noaa
                        </small>
                    </p>
                </blockquote>
            </div>
            
        </div>
    </div>
</div>-->

calculatorPlus/src/main/webapp/pages/login.jsp
<div class="col-md-6">
    <div class="card card-user">
        <div class="card-header">
            <h5 class="card-title">Login</h5>
        </div>
        <div class="card-body">
            <form action="?ac=login" method="POST">
                <input type="hidden" name="ac" value="login"/>
                <div class="row">
                    <div class="col-md-11 pr-1">
                        <div class="form-group">
                            <label>LOGIN</label>
                            <input type="text" class="form-control" name="cpLogin" required="true" placeholder="Login" 
                                   value="${requestScope.usr.nome}">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-11 pr-1">
                        <div class="form-group">
                            <label>SENHA</label>
                            <input type="password" class="form-control" name="cpSenha" required="true" placeholder="Senha" 
                                   value="${requestScope.usr.email}">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="update ml-auto mr-auto">
                        <button type="submit" class="btn btn-primary btn-round">logar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

calculatorPlus/src/main/webapp/pages/ranking.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title"> 
                <i class="nc-icon nc-trophy"></i>
                Ranking Geral</h4>
            <p class="category">Competições entre Alunos</p>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                        <tr><th>
                                Nome
                            </th>
                            <th>
                                Bonificação
                            </th>
                            <th>
                                Tempo de Jogo
                            </th>
                            <th >
                                Competições
                            </th>
                            <th class="text-right">
                                ...
                            </th>
                        </tr></thead>
                    <tbody>
                        <c:forEach items="${requestScope.ranking}" var="c" >
                            <tr>
                                <td>
                                    ${ c.nome}
                                </td>
                                <td>
                                    Cr$ ${c.bonusFormatado}
                                </td>
                                <td>
                                    ${c.tempo} minutos
                                </td>
                                <td>
                                    ${c.numeroCompeticoes}
                                </td>
                                <td class="text-right">
                                   ...
                                </td>
                            </tr>
                        </c:forEach>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>